# ##orignal
# # Resolve react_native_pods.rb with node to allow for hoisting
# require Pod::Executable.execute_command('node', ['-p',
#   'require.resolve(
#     "react-native/scripts/react_native_pods.rb",
#     {paths: [process.argv[1]]},
#   )', __dir__]).strip

# platform :ios, min_ios_version_supported
# prepare_react_native_project!
# use_modular_headers!

# linkage = ENV['USE_FRAMEWORKS']
# if linkage != nil
#   Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
#   use_frameworks! :linkage => linkage.to_sym
# end

# target 'AwesomeProject' do
#   config = use_native_modules!

#   use_frameworks! :linkage => :static
#   $RNFirebaseAsStaticFramework = true
#   use_react_native!(
#     :path => config[:reactNativePath],
#     # An absolute path to your application root.
#     :app_path => "#{Pod::Config.instance.installation_root}/..",
#     :hermes_enabled => false   # 👈 explicitly enable (or set to false to debug)
#   )

#   post_install do |installer|
#     # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
#     react_native_post_install(
#       installer,
#       config[:reactNativePath],
#       :mac_catalyst_enabled => false,
#       # :ccache_enabled => true
#     )
#   end
# end



############


# ##orignal
#   def node_require(script)
#     # Resolve script with node to allow for hoisting
#     require Pod::Executable.execute_command('node', ['-p',
#       "require.resolve(
#         '#{script}',
#         {paths: [process.argv[1]]},
#       )", __dir__]).strip
#   end

# # Use it to require both react-native's and this package's scripts:
#   node_require('react-native/scripts/react_native_pods.rb')
#   node_require('react-native-permissions/scripts/setup.rb')

# platform :ios, min_ios_version_supported
# prepare_react_native_project!
# # ⬇️ uncomment the permissions you need
# setup_permissions([
#   # 'AppTrackingTransparency',
#   # 'Bluetooth',
#   # 'Calendars',
#   # 'CalendarsWriteOnly',
#   # 'Camera',
#   # 'Contacts',
#   # 'FaceID',
#   # 'LocationAccuracy',
#   # 'LocationAlways',
#   # 'LocationWhenInUse',
#   # 'MediaLibrary',
#   # 'Microphone',
#   # 'Motion',
#   # 'Notifications',
#   # 'PhotoLibrary',
#   # 'PhotoLibraryAddOnly',
#   # 'Reminders',
#   # 'Siri',
#   # 'SpeechRecognition',
#   # 'StoreKit',
# ])

# use_modular_headers!

# linkage = ENV['USE_FRAMEWORKS']
# if linkage != nil
#   Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
#   use_frameworks! :linkage => linkage.to_sym
# end

# target 'AwesomeProject' do
#   config = use_native_modules!

#   use_frameworks! :linkage => :static
#   $RNFirebaseAsStaticFramework = true
#   use_react_native!(
#     :path => config[:reactNativePath],
#     # An absolute path to your application root.
#     :app_path => "#{Pod::Config.instance.installation_root}/..",
#     :hermes_enabled => false   # 👈 explicitly enable (or set to false to debug)
#   )

#   post_install do |installer|
#     # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
#     react_native_post_install(
#       installer,
#       config[:reactNativePath],
#       :mac_catalyst_enabled => false,
#       # :ccache_enabled => true
#     )
#   end
# end


#####
##done changes for permissions
def node_require(script)
  # Resolve script with node to allow for hoisting
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve(
      '#{script}',
      {paths: [process.argv[1]]},
    )", __dir__]).strip
end

# Require React Native + RNPermissions scripts
node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')

platform :ios, min_ios_version_supported
prepare_react_native_project!

# Enable only what you actually use
setup_permissions([
  'LocationWhenInUse',
  'Camera',
    'AppTrackingTransparency',

  'Calendars',
  'CalendarsWriteOnly',
  'Camera',
  'Contacts',
  'FaceID',
  'LocationAccuracy',
  'LocationAlways',
  'LocationWhenInUse',
  'MediaLibrary',
  'Microphone',

  'Notifications',
  'PhotoLibrary',
  'PhotoLibraryAddOnly',
  'Reminders',

  'SpeechRecognition',
  'StoreKit',
])

use_modular_headers!

target 'AwesomeProject' do
  config = use_native_modules!

  use_frameworks! :linkage => :static
  $RNFirebaseAsStaticFramework = true

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :hermes_enabled => false
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
    )
  end
end
